### Adapted from: git@github.com:choppsv1/ietf-docs.git
### Adapted from: git@github.com:rolandwalker/emacs-travis.git
###
### Notes
###
### The travis web interface may choke silently and fail to
### update when there are issues with the .travis.yml file.
###
### The "travis-lint" command-line tool does not catch all
### errors which may lead to silent failure.
###
### Shell-style comments in this file must have "#" as the
### *first* character of the line.
###

###
### language
###

# travis-lint no longer permits this value
dist: xenial
language: generic
sudo: true

###
### defining the build matrix
###
### ===>                                                       <===
### ===> each variation in env/matrix will be built and tested <===
### ===>                                                       <===
###
### variables under env/global are available to the build process
### but don't cause the creation of a separate variation
###

env:
  - EVM_EMACS=emacs-25.1-travis
#   - EVM_EMACS=emacs-25.2-travis
#   - EVM_EMACS=emacs-25.3-travis

# - sudo emacs --batch --eval '(package-install "org")' || true
#   - sudo apt-get -y update
#   - sudo apt-get -y install tidy

before_install:
  - sudo apt-get -y install tidy
  - sudo apt-get install -y emacs24 || true

#  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
#  - evm install $EVM_EMACS --use --skip
#  - cask

script:
  - emacs --version
  - make test

# matrix:
#   include:
#     - env: EMACS=emacs23
#     - env: EMACS=emacs24
#       addons:
#         apt:
#            packages:
#            - emacs24-nox
