#+OPTIONS: prop:nil title:t toc:nil \n:nil ::t |:t ^:{} -:t *:t ':t

* Org Mode RFC (~xml2rfc~) Exporter ~ox-rfc.el~

[[https://travis-ci.org/choppsv1/ietf-docs][https://travis-ci.org/choppsv1/ietf-docs.svg?branch=master]]

This is an org mode export back-end to convert an Org mode formatted file into
~xml2rfc~ RFC format. Its direct output is XML that can be input to ~xml2rfc~ to
further format the file into text, HTML or PDF formats. The code does make some
assumptions about the organization of the Org mode file in order to properly
produce and correct RFC formatted and organized file.

Exporting directly to text, HTML and PDF is supported by automatically running
~xml2rfc~ on the exported XML; however, this document does not including details
on setting up ~xml2rfc~ (=pip install xml2rfc= usually works though!)

This software is seen as a good start, but there's plenty of room for
improvements and adding more features. I'm certainly hoping that others will
also help with contributions to improve the code.

** Quick Install/Use with Makefile:

MELPA integration is taking a while, in the meantime you can use a makefile rule
to export your ORG as xml2rfc outputs

#+begin_src makefile
  ORG := example.org
  BASE := $(shell sed -e '/^\#+RFC_NAME:/!d;s/\#+RFC_NAME: *\(.*\)/\1/' $(ORG))
  VERSION := $(shell sed -e '/^\#+RFC_VERSION:/!d;s/\#+RFC_VERSION: *\([0-9]*\)/\1/' $(ORG))
  all: $(BASE).xml $(BASE)-$(VERSION).txt
  clean:
          rm ${BASE}*.{xml,txt,html,pdf}
  ox-rfc.el:
          curl -fLO 'https://raw.githubusercontent.com/choppsv1/org-rfc-export/master/ox-rfc.el'
  $(BASE).xml: $(ORG) ox-rfc.el
          emacs -Q --batch --eval '(setq org-confirm-babel-evaluate nil)' -l ./ox-rfc.el $< -f ox-rfc-export-to-xml
  %-$(VERSION).txt: %.xml
          xml2rfc --text -o $@ $<
#+end_src


** Formatting of this document.

This document is formatted in Org mode. If you are viewing it normal ASCII then
remember that "=" and "~" characters are used for highlighting literal text
(e.g., verbatim or code) and should not be included if being used in an example.

** Required Document Structure

The following is the expected structure of the Org mode RFC file:

- Headlined Sections
- Headline "References"
  - Headline "Normative References"
  - Headline "Informative References"
- Appendix Sections.

Additionally the following may appear anywhere; however, the first two make he
most sense to be placed at the top of the file:

- Required and optional export variable settings.
- Abstract export block
- Example, Quote and Source blocks.
- Lists
- Tables

*** Required and option export variables
**** Required export variables:

A few variables need to always be set. They are listed here:

#+begin_example
  ,#+AUTHOR:
  ,#+TITLE:
  ,#+RFC_VERSION: 00
#+end_example

The ~RFC_VERSION~ is the standard Internet Draft version number (i.e., 2 base-10
digits with versions 0-9 given as 00-09).

**** Optional export variables:

#+begin_example
  ,#+AFFILIATION:
  ,#+EMAIL:
  ,#+RFC_AUTHORS:
  ,#+RFC_CATEGORY: std
  ,#+RFC_CONSENSUS: true
  ,#+RFC_IPR: trust200902
  ,#+RFC_NAME:
  ,#+RFC_OBSOLETES:
  ,#+RFC_STREAM: "IETF"
  ,#+RFC_UPDATES:
  ,#+RFC_XML_VERSION: "3"
#+end_example

- RFC_AUTHORS :: For multiple author documents. should be used and should be
                 specified using a lisp list syntax:
                 ~(("Ed Li" "el@foo.com" "Foo LLC") ("Joe Rix" "jr@bar.com" "Bar Co"))~).
- RFC_CATEGORY :: the ~category <rfc>~ attribute (default "std").
- RFC_CONSENSUS :: the ~consensus <rfc>~ attribute (default "true").
- RFC_IPR :: the ~ipr <rfc>~ attribute (default "trust200902").
- RFC_NAME :: The base name of the internet draft, if not specified the Org file
              name is used.
- RFC_OBSOLETES :: Comma separated list of RFCs this document obsoletes.
- RFC_STREAM :: The ~submissionType <rfc>~ attribute (default "IETF").
- RFC_UPDATES :: Comma separated list of RFCs this document updates.
- RFC_XML_VERSION :: The ~version <rfc>~ attribute (default "3").

The ~toc~ export setting for generating a table of contents is honored.

In addition it's usually a good idea to disable automatic superscript and
subscript processing (changing it to ={}= is suggested) otherwise words with
embedded underscores ('_') will transcode to subscripts.

Here's what I use for the standard export options:

#+begin_example
  # Do: title, toc:table-of-contents ::fixed-width-sections |tables
  # Do: ^:sup/sub with curly -:special-strings *:emphasis
  # Don't: prop:no-prop-drawers \n:preserve-linebreaks ':use-smart-quotes
  ,#+OPTIONS: prop:nil title:t toc:t \n:nil ::t |:t ^:{} -:t *:t ':nil
#+end_example

*** Abstract

A special export block must be used to specify and abstract it looks like so:

#+begin_example
  ,#+beging_abstract
  This is the abstract of a document.
  ,#+end_abstract
#+end_example

*** Headlines

Normal Org mode headlined sections map to RFC sections. Headlines prior to the
"References" section are normal sections and headlines after "References" are
appendices.

*** References

The "References" headline expects 1 or 2 sub-sections titled "Normative
References" and/or "Informative References". It then expects the actual references
as sub-sub-section headlines below one of those 2 sub-section headlines.
~ox-rfc.el~ automatically expands certain standard references namely headline
names that start with: "I-D", "IEEE", or "RFC".

Additionally if no standard reference is available then the bibliographic
information may be specified as properties under the headline.

Finally a ~:REF_STDXML~ property may be used to refer to the standard XML
bibliogrpahic entry if one wishes to pick a different headline to refer to it
(i.e., different reference text for use in the document).

TODO: ~:REF_STDXML~ is currently broken.

Here's a full example:

#+caption: Example References Section.
#+begin_example
  ,* Refereneces
  ,** Normative Refereneces
  ,*** RFC2119
  ,** Informative Refereneces
  ,*** RFC7991
  ,*** W3GGEO
  :PROPERTIES:
  :REF_STDXML: W3C-CR-geolocation-API-20100907
  :END:
  ,*** StudyScarlet
  :PROPERTIES:
  :REF_TITLE: A Study In Scarlet
  :REF_AUTHOR: Sir Arthur Conan Doyle
  :REF_DATE: Nov 1887
  :REF_CONTENT: Beeton's Christmas Annual, Ward Lock & Co
  :END:
#+end_example

The Properties for creating a custom reference are as follows:

- REF_ANNOTATION :: A value for the ~<annotation>~ xml2rfc element.
- REF_AUTHOR :: Author. If multiple authors need to be specify use an list in
                elisp format (e.g., ~("Author One" "Author Two")~)
- REF_CONTENT :: The value for the ~<refcontent>~ xml2rfc element.
- REF_DATE :: The value should be given in emacs ~parse-time-string~ format.
- REF_STDXML :: The value should be the standard reference text (e.g., "RFC.0791").
- REF_TITLE :: Title of cited work.

** Features

*** Character Formatting
NOTE: XML2RFC version 3 format only.

*Bold*, /italic/, =verbatim= and ~code~ styles are mapped to the ~xml2rfc~ elements
~<strong>~, ~<em>~, ~<tt>~ and ~<tt>~ respectively.

*** Citations and Links.

Internal and external references are supported (TODO: test external). For
internal links one can reference any anchor or section including the
sub-sub-section headlines under in the "References" headline. So e.g., a
reference to RFC7991 would be given using =[[RFC7991]]= Org mode reference
format and then a sub-sub-section headline under "Informative References" would
simple be "RFC7991" which ~ox-rfc.el~ will translate.

*** Figures and Artwork (Examples and Source code).

~ox-rfc.el~ maps example and source blocks to ~xml2rfc~ ~<artwork>~ elements.
Additionally if a ~#+CAPTION:~ is given for the block then it the artwork will be
placed inside a ~<figure>~ element with the ~#+CAPTION:~ value as the caption.

*** Blockquotes

NOTE: XML2RFC version 3 format only.

~#+begin_quote~ blocks are supported by ~xml2rfc~ version 3 format
~<blockquote>~.

TODO: ~xml2rfc~ version 2 support needs to be supported using ~<artwork>~

*** Lists

Lists are transformed correctly. Numbered, unnumbered and definition lists all
being supported. Definition lists are better supported in ~xml2rfc~ version 3
format using ~<dl>~ lists rather than more generic ~hanging~ style list format
of ~xml2rfc~ version 2 format.

TODO: Some work could be done here to better support bullet styles and more
numbering formats.

*** Tables

Tables are translated to ~<thead>~, ~<tbody>~, ~<tr>~, ~<td>~ table elements if
~xml2rfc~ version 3 (the default), otherwise they are quoted in ~<artwork>~ for
~xml2rfc~ version 2 format.
