version: 2.1

references:
  main_test: &main_test
    description: "Emacs << parameters.erel >> "
    parameters:
      erel:
        description: "Version of Emacs to test with"
        type: string
    docker:
      - image: "choppsv1/org-rfc-test:<< parameters.erel >>"
    working_directory: ~/org-rfc-test
    steps:
      - checkout
      - run:
          command: "make ORG_RELEASE=${ORG_RELEASE} test"

# This sort of sucks, I want the names in the test
# so I can't actually use the parameter stuff
jobs:
  emacs24-org8.3:
    environment:
      ORG_RELEASE=8.3.6
    <<: *main_test
  emacs24-org9.0:
    environment:
      ORG_RELEASE=9.0.10
    <<: *main_test
  emacs24-org9.1:
    environment:
      ORG_RELEASE=9.1.14
    <<: *main_test
  emacs24-org9.2:
    environment:
      ORG_RELEASE=9.2.2
    <<: *main_test

  emacs25-org8.3:
    environment:
      ORG_RELEASE=8.3.6
    <<: *main_test
  emacs25-org9.0:
    environment:
      ORG_RELEASE=9.0.10
    <<: *main_test
  emacs25-org9.1:
    environment:
      ORG_RELEASE=9.1.14
    <<: *main_test
  emacs25-org9.2:
    environment:
      ORG_RELEASE=9.2.2
    <<: *main_test

  emacs26-org9.0:
    environment:
      ORG_RELEASE=9.0.10
    <<: *main_test
  emacs26-org9.1:
    environment:
      ORG_RELEASE=9.1.14
    <<: *main_test
  emacs26-org9.2:
    environment:
      ORG_RELEASE=9.2.2
    <<: *main_test


workflows:
  ox-rfc:
    jobs:
      - emacs24-org8.3:
          erel: "24.3"
      - emacs24-org9.0:
          erel: "24.3"
      - emacs24-org9.1:
          erel: "24.3"
      - emacs24-org9.2:
          erel: "24.3"

      - emacs25-org8.3:
          erel: "25.3"
      - emacs25-org9.0:
          erel: "25.3"
      - emacs25-org9.1:
          erel: "25.3"
      - emacs25-org9.2:
          erel: "25.3"

      - emacs26-org9.0:
          erel: "26.1"
      - emacs26-org9.1:
          erel: "26.1"
      - emacs26-org9.2:
          erel: "26.1"
