version: 2.1

jobs:
  test-emacs:
    working_directory: ~/org-rfc-test
    parameters:
      erel:
        description: "Version of Emacs to test with"
        type: string
        default: "24.3"
      orgrel:
        description: "Version of ORG to test with"
        type: string
        default: "8.3.6"
    docker:
      - image: "choppsv1/org-rfc-test:<< parameters.erel >>"
    steps:
      - checkout
      - run:
          name: "Test ox-rfc Emacs << parameters.erel >> ORG << parameters.orgrel >>"
          command: "make ORG_RELEASE=<< parameters.orgrel >> test"


workflows:
  test-ox-rfc:
    jobs:
      - test-emacs:
          erel: "24.3"
          orgrel: "8.3.6"
      - test-emacs:
          erel: "25.3"
          orgrel: "9.0.10"
      - test-emacs:
          erel: "26.1"
          orgrel: "9.0.10"
