version: 2.1

references:
  main_test: &main_test
    description: "Emacs << parameters.erel >> "
    parameters:
      erel:
        description: "Version of Emacs to test with"
        type: string
    docker:
      - image: "choppsv1/org-rfc-test:<< parameters.erel >>"
    working_directory: ~/org-rfc-test
    steps:
      - checkout
      - run:
          command: "make ORG_RELEASE=${ORG_RELEASE} test"

# This sort of sucks, I want the names in the test
# so I can't actually use the parameter stuff
jobs:
  emacs25-org93:
    environment:
      ORG_RELEASE=9.3.8
    <<: *main_test
  emacs25-org94:
    environment:
      ORG_RELEASE=9.4.4
    <<: *main_test
  emacs25-org95:
    environment:
      ORG_RELEASE=9.5.2
    <<: *main_test

  emacs26-org93:
    environment:
      ORG_RELEASE=9.3.8
    <<: *main_test
  emacs26-org94:
    environment:
      ORG_RELEASE=9.4.4
    <<: *main_test
  emacs26-org95:
    environment:
      ORG_RELEASE=9.5.2
    <<: *main_test

  emacs27-org93:
    environment:
      ORG_RELEASE=9.3.8
    <<: *main_test
  emacs27-org94:
    environment:
      ORG_RELEASE=9.4.4
    <<: *main_test
  emacs27-org95:
    environment:
      ORG_RELEASE=9.5.2
    <<: *main_test



workflows:
  ox-rfc:
    jobs:
      - emacs25-org93:
          erel: "25.3"
      # - emacs25-org94:
      #     erel: "25.3"
      # - emacs25-org95:
      #     erel: "25.3"

      # - emacs26-org93:
      #     erel: "26.1"
      - emacs26-org94:
          erel: "26.1"
      # - emacs26-org95:
      #     erel: "26.1"

      # - emacs27-org93:
      #     erel: "27.2"
      # - emacs27-org94:
      #     erel: "27.2"
      - emacs27-org95:
          erel: "27.2"
